M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-09-03T12:13:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-03T12:13:21-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X47.65Y-24.1
X52.35Y-24.1
T2
X24.0Y-24.0
X24.0Y-56.0
X76.0Y-24.0
X76.0Y-56.0
M30
